name: Ejecutar Sistema de Metraje

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ejecutar_proceso:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar Código
        uses: actions/checkout@v3

      - name: Instalar y Correr Todo
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pandas streamlit-gsheets-connection st-gsheets-connection gspread google-auth
          python app.py
