name: Ejecutar Script de Google
on:
  push:
    branches: [ main ]  # Se ejecuta cada vez que subas cambios
  workflow_dispatch:      # Permite ejecutarlo manualmente con un botón

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install gspread google-auth

      - name: Ejecutar el script
        env:
          # Conectamos cada Secret individual que creaste en GitHub
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: python app.py
